name: Subsonic Docker Build

on:
   schedule:
    - cron: '12 2 * * 6'
    
jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup qemu
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
          platforms: all
    - name: install buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
       version: latest
    - name: login to docker hub
      run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
    - name: build updated image
      run: |
        BDATE=$(date +%d-%m-%Y) && docker buildx build --push \
        --tag avpnusr/subsonic:latest --tag avpnusr/subsonic:$BDATE \
        --platform linux/amd64,linux/arm/v7,linux/arm/v6,linux/arm64 \
        --file ./Dockerfile .
    - name: Clean
      run: |
        rm -f ${HOME}/.docker/config.json
